name: Deploy
on:
  push:
    branches:
      - main

jobs:
  cache:
    name: Collect data from sheets
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install python deps
        run: pip install -r requirements.txt
      - name: copy latest from sheets
        run: python scripts/get-sheets.py
        env:
          G_SHEETS_API_KEY: ${{secrets.G_SHEETS_API_KEY}}
      - name: save results
        uses: actions/upload-artifact@v4
        with:
          name: json_all
          path: public/json

  build:
    name: Build static site
    needs: cache
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Download sheets data
        uses: actions/download-artifact@v4
        with:
          name: json_all
          path: public/json
      - name: install npm deps
        run: npm ci
      # https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions
      - name: nextjs build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: build site
        run: npm run build
      - name: upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

  deploy:
    name: Deploy to gh-pages
    needs: build
    runs-on: ubuntu-latest
    environment: production
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
